### ISSUE TITLE
trailingSemicolon linter breaks for @media queries with vars inside

### ISSUE THREAD

**Issue by kokarn** [jwilsson/lesshint#15]
Basic media query code as the one below errors with the message "All property declarations should end with a semicolon" on the second to last semicolon.

```
@media screen and ( max-width: 768px ){
    @color: red;

    .div {
        color: @color;
    }
}
```

**Comment by jwilsson** [comment]
Hmm, interesting. It seems to be confused by the variable declaration. Just setting `red` as a value works as expected, i.e.

    @media screen and ( max-width: 768px ){
        .div {
            color: red;
        }
    }

works.

I'll take a look!
