### ISSUE TITLE
urlFormat and urlQuotes linters broken?

### ISSUE THREAD

**Issue by kokarn** [jwilsson/lesshint#22]
Tried with this code
```
div {
    background-image: url( 'http://placekitten.com/g/1200/600' );
}
```
The only error I get is this
>test.less: line 2, col 23, urlQuotes: URLs should enclosed in quotes.

Shouldn't I get an error that the format is incorrect and no error on the quotes?

**Comment by jwilsson** [comment]
Should be fixed with 81ed97e7b28dced17c819deab1ab942d0d6ab380 and daff331ce15729ad2236f5a66e929ff3c2f65796.

Thanks!
