### ISSUE TITLE
Lesshint fails if the .lesshintrc file is empty

### ISSUE THREAD

**Issue by kokarn** [jwilsson/lesshint#29]
This seems to be intended but wouldn't it be a bit more helpful if it just produces a warning and uses defaults instead?

**Comment by jwilsson** [comment]
Yeah, I'll look into that.

**Comment by jwilsson** [comment]
I've been thinking and I think we should keep the current behaviour.

If a user has added a `.lesshintrc` file it should contain something that's valid JSON (comments aside) and an empty file isn't valid so it should bail.

Since you do get a error message/exception?

**Comment by kokarn** [comment]
Hmm, yeah that's true i guess.

The current error is ```Something's wrong with the config file. Error: Unexpected end of input```
Maybe a clarification would be nice?

**Comment by jwilsson** [comment]
We're just printing whatever `JSON.parse()` throws at us and one could argue that empty input is an "Unexpected end" of it :wink: 

Anyway, I'm closing this for now. We can always revisit it in the future.
