### ISSUE TITLE
Try to add reasoning to defaults

### ISSUE THREAD

**Issue by kokarn** [jwilsson/lesshint#9]
It would be good for educational purposes to see what the reasoning behind each default is. 
Also it will probably spark discussion further down the line which is always a good thing.

**Comment by jwilsson** [comment]
Just to clarify: in the issues, the readme or both, perhaps?

**Comment by kokarn** [comment]
I feel like Issues are mostly for discussion so it doesn't matter as much. But in the readme I think it would be nice.

**Comment by jwilsson** [comment]
Good point, I'll add it!
